version: 2
release:
  github:
    owner: synthient
    name: 'cli'
  prerelease: auto
before:
  hooks:
    - go mod download
builds:
  - id: synthient
    main: ./cmd
    binary: synthient
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
homebrew_casks:
  - name: synthient
    url:
      template: 'https://github.com/synthient/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    homepage: https://github.com/synthient/cli
    description: Official CLI for synthient
    zap:
      delete:
        - ~/.config/synthient
    repository:
      owner: synthient
      name: homebrew-tap
