version: 2
project_name: synthient
release:
  github:
    owner: synthient
    name: 'cli'
  prerelease: auto
before:
  hooks:
    - go mod download
    - ./completions.sh
builds:
  - id: synthient
    main: ./cmd/synthient
    binary: synthient
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: synthient
    files:
      - LICENSE
      - README.md
      - completions/*
homebrew_casks:
  - name: synthient
    url:
      template: 'https://github.com/synthient/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    homepage: https://github.com/synthient/cli
    description: Official CLI for synthient
    completions:
      bash: completions/synthient.bash
      zsh: completions/synthient.zsh
      fish: completions/synthient.fish
    zap:
      delete:
        - ~/.config/synthient
    repository:
      owner: synthient
      name: homebrew-tap
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synthient"]
          end
